#!/bin/sh
# -*- coding:utf-8 -*-

###
# File: stopwatch
# Project: smallscripts/stopwatch
# Created: 2018-02-27 [Tue] 03:10:42 +0900
# Author: H.Maruyama
# -----
# Last Modified: 2018-02-27 [Tue] 03:28:08 +0900
# Modified By: H.Maruyama
# -----
# Copyright (C) 2018 H.Maruyama(WASSHA Inc.)
# License: GNU General Public License v3.0 or later
# License URL: http://www.gnu.org/licenses/gpl-3.0-standalone.html
###

date1=`date +%s`;
while true; do 
    echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
done
